In [1]:
import numpy as np 
import pandas as pd 
import random

In [5]:
data = 

TypeError: random_sample() takes at most 1 positional argument (3 given)

In [4]:
points

[[2, 3, 5],
 [3, 4, 6],
 [4, 3, 5],
 [5, 4, 6],
 [6, 3, 5],
 [8, 7, 9],
 [9, 8, 10],
 [10, 7, 9],
 [11, 8, 10],
 [12, 7, 9],
 [5, 5, 2],
 [6, 5, 2],
 [5, 6, 3],
 [6, 6, 3],
 [7, 6, 2]]

In [13]:
def minkowski_distance(p1, p2, p=3):
    p1 = np.array(p1)
    p2 = np.array(p2)
    
    point_sum = np.sum(np.abs(p1 - p2)**p)
    
    return point_sum**(1/p)

In [14]:


def find_new_centroid(clusters):
    new_centroids = {}

    for cluster_index, points in clusters.items():
        if len(points) > 0:
            cluster_mean = np.mean(points, axis=0)
            new_centroids[cluster_index] = cluster_mean.tolist()
        else:
            new_centroids[cluster_index] = None  # Handle empty clusters

    return new_centroids


In [15]:
def kmeans_modified(points, k1=2, k2=3, margin=0.008, max_iters=1000):
    if len(points) < k1 + k2:
        raise ValueError("Insufficient points for the specified cluster sizes")

    # Initialize centroids for the first two clusters
    centroids = np.array(random.sample(points, k1 + k2))

    # Ensure that the first cluster has 2 points and the second cluster has 3 points
    clusters = {i: [] for i in range(k1 + k2)}
    for i in range(k1 + k2):
        clusters[i].append(centroids[i])

    # Assign the remaining points to the nearest cluster using Minkowski distance with p=3
    remaining_points = [point for point in points if point not in centroids]
    for point in remaining_points:
        distances = [minkowski_distance(point, centroid, p=3) for centroid in centroids]
        nearest_cluster = np.argmin(distances)
        clusters[nearest_cluster].append(point)

    print("Initial centroids", centroids)

    for _ in range(max_iters):
        # Calculate new centroids
        new_centroids = {i: np.mean(cluster, axis=0) for i, cluster in clusters.items()}

        print("Final centroids", new_centroids)

        # Check for convergence
        if np.linalg.norm(np.array(list(new_centroids.values())) - centroids) <= margin:
            break

        centroids = np.array(list(new_centroids.values()))

        # Update clusters based on the new centroids and Minkowski distance with p=3
        clusters = {i: [] for i in range(k1 + k2)}
        for point in points:
            distances = [minkowski_distance(point, centroid, p=3) for centroid in centroids]
            nearest_cluster = np.argmin(distances)
            clusters[nearest_cluster].append(point)

    return clusters


In [16]:
clusters = kmeans(points, 3)

Initial centroid [[ 4  3  5]
 [ 8  7  9]
 [10  7  9]]
Final centroid [[ 4.9         4.5         3.9       ]
 [ 8.5         7.5         9.5       ]
 [11.          7.33333333  9.33333333]]
Final centroid [[ 4.9         4.5         3.9       ]
 [ 8.5         7.5         9.5       ]
 [11.          7.33333333  9.33333333]]


In [17]:
clusters

{0: [[2, 3, 5],
  [3, 4, 6],
  [4, 3, 5],
  [5, 4, 6],
  [6, 3, 5],
  [5, 5, 2],
  [6, 5, 2],
  [5, 6, 3],
  [6, 6, 3],
  [7, 6, 2]],
 1: [[8, 7, 9], [9, 8, 10]],
 2: [[10, 7, 9], [11, 8, 10], [12, 7, 9]]}